// <auto-generated />
using System;
using LaoCai.SoftwareManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LaoCai.SoftwareManagement.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260921045917_AddPhase3Entities")]
    partial class AddPhase3Entities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Audit.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("AfterJson")
                        .HasColumnType("text")
                        .HasColumnName("after_json");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("text")
                        .HasColumnName("before_json");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("OrganizationId", "OccurredAt")
                        .HasDatabaseName("ix_audit_logs_organization_id_occurred_at");

                    b.ToTable("audit_logs", "audit");
                });

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Catalog.CatalogProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("CreatedSoftwareId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_software_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("ProposedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposed_by_user_id");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<string>("SoftwareName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("software_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_catalog_proposals");

                    b.HasIndex("CreatedSoftwareId")
                        .HasDatabaseName("ix_catalog_proposals_created_software_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_catalog_proposals_organization_id");

                    b.HasIndex("ProposedByUserId")
                        .HasDatabaseName("ix_catalog_proposals_proposed_by_user_id");

                    b.HasIndex("ReviewedByUserId")
                        .HasDatabaseName("ix_catalog_proposals_reviewed_by_user_id");

                    b.ToTable("catalog_proposals", "catalog");
                });

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Catalog.Software", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("LifecycleStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lifecycle_status");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_software");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_software_category_id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_software_code");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_software_vendor_id");

                    b.ToTable("software", "catalog");
                });

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Catalog.SoftwareCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_software_categories");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_software_categories_code");

                    b.ToTable("software_categories", "catalog");
                });

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Catalog.SoftwareRelease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("release_date");

                    b.Property<Guid>("SoftwareId")
                        .HasColumnType("uuid")
                        .HasColumnName("software_id");

                    b.Property<DateTime?>("SupportEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("support_end_date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("VersionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("version_name");

                    b.HasKey("Id")
                        .HasName("pk_software_releases");

                    b.HasIndex("SoftwareId", "VersionName")
                        .IsUnique()
                        .HasDatabaseName("ix_software_releases_software_id_version_name");

                    b.ToTable("software_releases", "catalog");
                });

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Catalog.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("ContactInfo")
                        .HasColumnType("text")
                        .HasColumnName("contact_info");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_vendors");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_vendors_code");

                    b.ToTable("vendors", "catalog");
                });

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Deployments.ApprovalDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTime>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("decision");

                    b.Property<Guid>("DeploymentRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("deployment_revision_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_approval_decisions");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("ix_approval_decisions_actor_id");

                    b.HasIndex("DeploymentRevisionId")
                        .HasDatabaseName("ix_approval_decisions_deployment_revision_id");

                    b.ToTable("approval_decisions", "deployments");
                });

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Deployments.Deployment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("CurrentApprovedRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_approved_revision_id");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("environment");

                    b.Property<string>("InstanceKey")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("default")
                        .HasColumnName("instance_key");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("SoftwareId")
                        .HasColumnType("uuid")
                        .HasColumnName("software_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_deployments");

                    b.HasIndex("CurrentApprovedRevisionId")
                        .HasDatabaseName("ix_deployments_current_approved_revision_id");

                    b.HasIndex("OrganizationId", "SoftwareId")
                        .HasDatabaseName("ix_deployments_organization_id_software_id");

                    b.HasIndex("SoftwareId", "OrganizationId", "Environment", "InstanceKey")
                        .IsUnique()
                        .HasDatabaseName("ix_deployments_software_id_organization_id_environment_instanc");

                    b.ToTable("deployments", "deployments");
                });

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Deployments.DeploymentRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("deployment_id");

                    b.Property<DateOnly?>("GoLiveDate")
                        .HasColumnType("date")
                        .HasColumnName("go_live_date");

                    b.Property<string>("OperationalStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("operational_status");

                    b.Property<Guid?>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<Guid?>("ResponsibleUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("responsible_user_id");

                    b.Property<int>("RevisionNo")
                        .HasColumnType("integer")
                        .HasColumnName("revision_no");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid?>("SubmittedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<string>("WorkflowStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Draft")
                        .HasColumnName("workflow_status");

                    b.HasKey("Id")
                        .HasName("pk_deployment_revisions");

                    b.HasIndex("DeploymentId")
                        .IsUnique()
                        .HasDatabaseName("ix_deployment_revisions_active")
                        .HasFilter("\"workflow_status\" IN ('Draft', 'Submitted')");

                    b.HasIndex("ReleaseId")
                        .HasDatabaseName("ix_deployment_revisions_release_id");

                    b.HasIndex("ResponsibleUserId")
                        .HasDatabaseName("ix_deployment_revisions_responsible_user_id");

                    b.HasIndex("SubmittedBy")
                        .HasDatabaseName("ix_deployment_revisions_submitted_by");

                    b.HasIndex("DeploymentId", "ApprovedAt")
                        .HasDatabaseName("ix_deployment_revisions_deployment_id_approved_at");

                    b.HasIndex("DeploymentId", "RevisionNo")
                        .IsUnique()
                        .HasDatabaseName("ix_deployment_revisions_deployment_id_revision_no");

                    b.HasIndex("WorkflowStatus", "DeploymentId")
                        .HasDatabaseName("ix_deployment_revisions_workflow_status_deployment_id");

                    b.ToTable("deployment_revisions", "deployments");
                });

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Iam.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("group_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_permissions_code");

                    b.ToTable("permissions", "iam");
                });

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Iam.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_code");

                    b.ToTable("roles", "iam");
                });

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Iam.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.ToTable("role_permissions", "iam");
                });

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Iam.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("security_stamp");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ix_users_normalized_user_name");

                    b.ToTable("users", "iam");
                });

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Iam.UserRoleScope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IncludeDescendants")
                        .HasColumnType("boolean")
                        .HasColumnName("include_descendants");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("scope_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_user_role_scopes");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_role_scopes_role_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_role_scopes_user_id");

                    b.ToTable("user_role_scopes", "iam");
                });

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Jobs.BackgroundJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lease_owner");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_token");

                    b.Property<DateTime?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_until");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<DateTime>("NextRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_run_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Queued")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_background_jobs");

                    b.HasIndex("Status", "NextRunAt", "LeaseUntil")
                        .HasDatabaseName("ix_background_jobs_status_next_run_at_lease_until");

                    b.ToTable("background_jobs", "jobs");
                });

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Jobs.IdempotencyRecord", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_hash");

                    b.Property<string>("RequestPath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("request_path");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("response_body");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Key")
                        .HasName("pk_idempotency_records");

                    b.ToTable("idempotency_records", "jobs");
                });

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeduplicationKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("deduplication_key");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_user_id");

                    b.Property<string>("TargetRoute")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("target_route");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("DeduplicationKey")
                        .IsUnique()
                        .HasDatabaseName("ix_notifications_deduplication_key")
                        .HasFilter("\"deduplication_key\" IS NOT NULL");

                    b.HasIndex("RecipientUserId", "ReadAt", "CreatedAt")
                        .HasDatabaseName("ix_notifications_recipient_user_id_read_at_created_at");

                    b.ToTable("notifications", "notifications");
                });

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_organizations_code");

                    b.ToTable("organizations", "organizations");
                });

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Organizations.OrganizationSuccession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_date");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid>("PredecessorId")
                        .HasColumnType("uuid")
                        .HasColumnName("predecessor_id");

                    b.Property<Guid>("SuccessorId")
                        .HasColumnType("uuid")
                        .HasColumnName("successor_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_organization_successions");

                    b.HasIndex("PredecessorId")
                        .HasDatabaseName("ix_organization_successions_predecessor_id");

                    b.HasIndex("SuccessorId")
                        .HasDatabaseName("ix_organization_successions_successor_id");

                    b.ToTable("organization_successions", "organizations");
                });

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Organizations.OrganizationVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_organization_versions");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_organization_versions_parent_id");

                    b.HasIndex("OrganizationId", "ValidFrom")
                        .HasDatabaseName("ix_organization_versions_organization_id_valid_from");

                    b.ToTable("organization_versions", "organizations");
                });

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Catalog.CatalogProposal", b =>
                {
                    b.HasOne("LaoCai.SoftwareManagement.Domain.Entities.Catalog.Software", "CreatedSoftware")
                        .WithMany()
                        .HasForeignKey("CreatedSoftwareId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_catalog_proposals_software_created_software_id");

                    b.HasOne("LaoCai.SoftwareManagement.Domain.Entities.Organizations.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_catalog_proposals_organizations_organization_id");

                    b.HasOne("LaoCai.SoftwareManagement.Domain.Entities.Iam.User", "ProposedByUser")
                        .WithMany()
                        .HasForeignKey("ProposedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_catalog_proposals_users_proposed_by_user_id");

                    b.HasOne("LaoCai.SoftwareManagement.Domain.Entities.Iam.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_catalog_proposals_users_reviewed_by_user_id");

                    b.Navigation("CreatedSoftware");

                    b.Navigation("Organization");

                    b.Navigation("ProposedByUser");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Catalog.Software", b =>
                {
                    b.HasOne("LaoCai.SoftwareManagement.Domain.Entities.Catalog.SoftwareCategory", "Category")
                        .WithMany("SoftwareList")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_software_software_categories_category_id");

                    b.HasOne("LaoCai.SoftwareManagement.Domain.Entities.Catalog.Vendor", "Vendor")
                        .WithMany("SoftwareList")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_software_vendors_vendor_id");

                    b.Navigation("Category");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Catalog.SoftwareRelease", b =>
                {
                    b.HasOne("LaoCai.SoftwareManagement.Domain.Entities.Catalog.Software", "Software")
                        .WithMany("Releases")
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_software_releases_software_software_id");

                    b.Navigation("Software");
                });

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Deployments.ApprovalDecision", b =>
                {
                    b.HasOne("LaoCai.SoftwareManagement.Domain.Entities.Iam.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_approval_decisions_users_actor_id");

                    b.HasOne("LaoCai.SoftwareManagement.Domain.Entities.Deployments.DeploymentRevision", "DeploymentRevision")
                        .WithMany("Decisions")
                        .HasForeignKey("DeploymentRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_approval_decisions_deployment_revisions_deployment_revision");

                    b.Navigation("Actor");

                    b.Navigation("DeploymentRevision");
                });

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Deployments.Deployment", b =>
                {
                    b.HasOne("LaoCai.SoftwareManagement.Domain.Entities.Deployments.DeploymentRevision", "CurrentApprovedRevision")
                        .WithMany()
                        .HasForeignKey("CurrentApprovedRevisionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_deployments_deployment_revisions_current_approved_revision_");

                    b.HasOne("LaoCai.SoftwareManagement.Domain.Entities.Organizations.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_deployments_organizations_organization_id");

                    b.HasOne("LaoCai.SoftwareManagement.Domain.Entities.Catalog.Software", "Software")
                        .WithMany()
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_deployments_software_software_id");

                    b.Navigation("CurrentApprovedRevision");

                    b.Navigation("Organization");

                    b.Navigation("Software");
                });

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Deployments.DeploymentRevision", b =>
                {
                    b.HasOne("LaoCai.SoftwareManagement.Domain.Entities.Deployments.Deployment", "Deployment")
                        .WithMany("Revisions")
                        .HasForeignKey("DeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deployment_revisions_deployments_deployment_id");

                    b.HasOne("LaoCai.SoftwareManagement.Domain.Entities.Catalog.SoftwareRelease", "Release")
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_deployment_revisions_software_releases_release_id");

                    b.HasOne("LaoCai.SoftwareManagement.Domain.Entities.Iam.User", "ResponsibleUser")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_deployment_revisions_users_responsible_user_id");

                    b.HasOne("LaoCai.SoftwareManagement.Domain.Entities.Iam.User", "SubmittedByUser")
                        .WithMany()
                        .HasForeignKey("SubmittedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_deployment_revisions_users_submitted_by");

                    b.Navigation("Deployment");

                    b.Navigation("Release");

                    b.Navigation("ResponsibleUser");

                    b.Navigation("SubmittedByUser");
                });

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Iam.RolePermission", b =>
                {
                    b.HasOne("LaoCai.SoftwareManagement.Domain.Entities.Iam.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_id");

                    b.HasOne("LaoCai.SoftwareManagement.Domain.Entities.Iam.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Iam.UserRoleScope", b =>
                {
                    b.HasOne("LaoCai.SoftwareManagement.Domain.Entities.Iam.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_scopes_roles_role_id");

                    b.HasOne("LaoCai.SoftwareManagement.Domain.Entities.Iam.User", "User")
                        .WithMany("RoleScopes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_scopes_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Notifications.Notification", b =>
                {
                    b.HasOne("LaoCai.SoftwareManagement.Domain.Entities.Iam.User", "RecipientUser")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_recipient_user_id");

                    b.Navigation("RecipientUser");
                });

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Organizations.OrganizationSuccession", b =>
                {
                    b.HasOne("LaoCai.SoftwareManagement.Domain.Entities.Organizations.Organization", "Predecessor")
                        .WithMany()
                        .HasForeignKey("PredecessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organization_successions_organizations_predecessor_id");

                    b.HasOne("LaoCai.SoftwareManagement.Domain.Entities.Organizations.Organization", "Successor")
                        .WithMany()
                        .HasForeignKey("SuccessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organization_successions_organizations_successor_id");

                    b.Navigation("Predecessor");

                    b.Navigation("Successor");
                });

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Organizations.OrganizationVersion", b =>
                {
                    b.HasOne("LaoCai.SoftwareManagement.Domain.Entities.Organizations.Organization", "Organization")
                        .WithMany("Versions")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_versions_organizations_organization_id");

                    b.HasOne("LaoCai.SoftwareManagement.Domain.Entities.Organizations.Organization", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_organization_versions_organizations_parent_id");

                    b.Navigation("Organization");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Catalog.Software", b =>
                {
                    b.Navigation("Releases");
                });

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Catalog.SoftwareCategory", b =>
                {
                    b.Navigation("SoftwareList");
                });

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Catalog.Vendor", b =>
                {
                    b.Navigation("SoftwareList");
                });

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Deployments.Deployment", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Deployments.DeploymentRevision", b =>
                {
                    b.Navigation("Decisions");
                });

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Iam.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Iam.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Iam.User", b =>
                {
                    b.Navigation("RoleScopes");
                });

            modelBuilder.Entity("LaoCai.SoftwareManagement.Domain.Entities.Organizations.Organization", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
